name: general_repository
description: A general api repository to handle API responses
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  authentication_repository:
    path: ../authentication_repository
  http: ^1.3.0
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
