name: kinetic_energy_mobileapp
description: "A icecream selling e-commerce app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  general_repository:
    path: packages/general_repository
  authentication_repository:
    path: packages/authentication_repository
  cache:
    path: packages/cache
  localization:
    path: packages/localization


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  http: ^1.3.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  crypto: ^3.0.6
  flutter_web_auth_2: ^4.1.0
  location: ^8.0.0
  permission_handler: ^11.4.0
  formz: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0




flutter:


  uses-material-design: true

  assets:
    - assets/images/
