name: authentication_repository
description: Dart package which manages the authentication domain.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cache:
    path: ../cache
  general_repository:
    path: ../general_repository
  equatable: ^2.0.7
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  flutter_web_auth_2: ^4.1.0
  crypto: ^3.0.6
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
